name: Publish Python Package

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag that starts with 'v'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        pip install -e ".[dev]"  # Install your package in development mode with dev dependencies
    
    - name: Update version from tag
      run: |
        # Extract version from tag (without 'v' prefix)
        VERSION=${GITHUB_REF#refs/tags/v}
        # Update version in __version__.py
        echo "__version__ = \"$VERSION\"" > intura_ai/__version__.py
        # Display the version for verification
        echo "Publishing version: $VERSION"
        
    - name: Build and check package
      run: |
        python -m build
        twine check dist/*
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}